spring:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: true
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      data-locations: classpath*:data.sql
      mode: always

admin:
  email : mart@gmail.com, admin@gmail.com

jwt:
  secret: randomTestValueItisNotUsedInProdEnv
  expiration: 1800000000
  # 30 minutes
  refresh:
    expiration: 604800000
  # 7 days

---
spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: prod
